-- batch-02 — genererad 2026-06-07T06:55:49.200Z
begin;
update recipes set ingredients = ARRAY(SELECT jsonb_array_elements_text($q$["2 morötter","1 palsternacka","1 gul lök","1½ liter vatten","2 grönsaksbuljongtärningar","2 lagerblad","1 dl krossad vermicelli","2 msk finhackad persilja","neutral olja till stekning","örtsalt (t ex Vegeta allkrydda), efter smak","nymalen svartpeppar","Vitlöksbröd: 1 baguette","Vitlöksbröd: 50 g rumstempererat smör","Vitlöksbröd: 1 vitlöksklyfta, pressad","Vitlöksbröd: 2 msk finhackad persilja","Vitlöksbröd: salt"]$q$::jsonb))::text[] where id = 17; -- Soppa med vermicelli och rotfrukter
update recipes set ingredients = ARRAY(SELECT jsonb_array_elements_text($q$["ca 16 kokta potatisar","2 msk olivolja","2 dl finriven parmesan","flingsalt","2 dl crème fraiche","1 citron","salt och svartpeppar","400 g kallrökt lax i skivor","salladsblad, till servering"]$q$::jsonb))::text[] where id = 22; -- Parmesanpotatis med kallrökt lax
update recipes set ingredients = ARRAY(SELECT jsonb_array_elements_text($q$["4 dl blomkål, i bitar","4 msk olivolja","2 tsk malen spiskummin","2 tsk sambal oelek","salt","20 padrones","600–800 g färdig hummus","2 dl oliver och hackade soltorkade tomater","1 citron, pressad saft","libabröd (eller lantbröd), till servering"]$q$::jsonb))::text[] where id = 27; -- Hummusbowl
update recipes set ingredients = ARRAY(SELECT jsonb_array_elements_text($q$["3 vitlöksklyftor","150 g vitkål eller spetskål, strimlad","2 morötter","rapsolja, till stekning","1 msk gul currypulver","300 g nötfärs eller vegofärs","1 dl gröna ärtor","6–8 dl kokt ris (eller bulgur/matvete)","ca 2 msk japansk sojasås","strimlad salladslök, till servering","hackade nötter, till servering","Gott till: srirachasås"]$q$::jsonb))::text[] where id = 29; -- Stekt curryris med färs och salladslök
update recipes set ingredients = ARRAY(SELECT jsonb_array_elements_text($q$["3 vitlöksklyftor","1 röd chilifrukt","olivolja, till stekning","1 rejäl aubergine (ca 400 g)","0,75 dl torkade linser (t ex puy- eller belugalinser)","400 g passerade tomater","2 dl grädde (alternativt havregrädde)","2 msk tomatpuré","1 näve körsbärstomater (kan uteslutas)","1–2 msk japansk sojasås","torkad oregano, efter smak","svartpeppar","pasta för 4 personer"]$q$::jsonb))::text[] where id = 31; -- Pepprig pastasås med aubergine
update recipes set ingredients = ARRAY(SELECT jsonb_array_elements_text($q$["1 spetskålshuvud eller vitkål (ca 400 g)","1 kruka färsk koriander","2 gula lökar","4 vitlöksklyftor","rapsolja, till stekning","salt","2 tsk chiliflakes","2 msk smör","8 ägg","2 dl riven ost","4 stora tortillas","Till servering: chilisås"]$q$::jsonb))::text[] where id = 32; -- Breakfast burrito med kål och äggröra
update recipes set ingredients = ARRAY(SELECT jsonb_array_elements_text($q$["450 g potatis","1 stor gul lök","rapsolja, till stekning","salt","150 g grönkål","150 g riven gratängost","8 små tortillabröd","Syrlig koriandersås: 1 kruka färsk koriander","Syrlig koriandersås: 1 jalapeño","Syrlig koriandersås: 1 vitlöksklyfta","Syrlig koriandersås: 1 lime","Syrlig koriandersås: 3 msk olivolja","Syrlig koriandersås: 1 msk rostade sesamfrön","Syrlig koriandersås: salt"]$q$::jsonb))::text[] where id = 33; -- Krispiga ostquesadillas med grönkål och potatis med syrlig koriandersås
update recipes set ingredients = ARRAY(SELECT jsonb_array_elements_text($q$["Sojamajonnäs: 1 dl majonnäs","Sojamajonnäs: 1 tsk ljus soja","Sojamajonnäs: 1 tsk citronsaft","Sojamajonnäs: 1 tsk ljus sirap","Sojamajonnäs: 1 nypa salt","Pankopanerad tofu: 400 g tofu","Pankopanerad tofu: 2 dl rapsolja","Pankopanerad tofu: 2 dl vetemjöl","Pankopanerad tofu: 1 tsk salt","Pankopanerad tofu: 1 tsk chiliflakes","Pankopanerad tofu: 2 ägg","Pankopanerad tofu: 1 msk ljus soja","Pankopanerad tofu: 2–3 dl panko ströbröd","Kålsallad: ½ huvud spetskål (eller vitkål)","Kålsallad: 2 salladslökar","8 skivor brioche (ganska tjocka)"]$q$::jsonb))::text[] where id = 35; -- Katsu sando med panerad tofu och kålsallad
update recipes set ingredients = ARRAY(SELECT jsonb_array_elements_text($q$["½ vitkålshuvud (ca 400 g)","1 stor gul lök","400 g potatis","zucchini (ca 400 g)","rapsolja, till stekning","salt","2 tsk tomatpuré","3 msk mjöl","4 tomater (ca 400 g)","½ dl crème fraiche","3 dl vatten","2–3 vitlöksklyftor","1 kruka färsk dill","1 citron","Till servering: baguette eller annat rustikt bröd"]$q$::jsonb))::text[] where id = 38; -- Sommargryta med vitkål, zucchini och dill
commit;
